- docs/debug_dump.txt
- pyfda/filter_design/firwin.py
- pyfda/filter_tree_builder.py
- pyfda/filterbroker.py
- pyfda/input_widgets/input_filter.py
- pyfda/input_widgets/input_info.py
- pyfda/input_widgets/input_order.py
- pyfda/input_widgets/input_specs.py
- pyfda/input_widgets/input_tab_widgets.py
- pyfda/pyfda.py
Move all the stuff for creating dynamic filter instances to filterbroker.py to make the code more robust and transparent. The PR doesn't fix the exit bug (unfortunately) but makes the code cleaner.
> Dyn filter instance

- pyfda/input_widgets/input_amp_specs.py
- pyfda/input_widgets/input_freq_specs.py
- pyfda/input_widgets/input_freq_units.py
- pyfda/input_widgets/input_specs.py
- pyfda/input_widgets/input_target_specs.py
- pyfda/input_widgets/input_weight_specs.py
- pyfda/pyfda_lib.py
Move the method _rt_label for creating rich text labels to pyfda_lib as a a function to reduce the overhead.
> Centralize functions

- pyfda/input_widgets/input_freq_specs.py
- pyfda/input_widgets/input_freq_units.py
- pyfda/input_widgets/input_specs.py
- pyfda/input_widgets/input_target_specs.py
- pyfda/plot_widgets/plot_hf.py
The graphical display of the filter specs has been improved, at the same time the python code for specifying the limits has been simplified.
> Improve plot specs

- pyfda/input_widgets/input_freq_units.py
- pyfda/plot_widgets/plot_3d.py
- pyfda/plot_widgets/plot_hf.py
- pyfda/plot_widgets/plot_impz.py
- pyfda/plot_widgets/plot_phi.py
- pyfda/plot_widgets/plot_pz.py
- pyfda/plot_widgets/plot_tab_widgets.py
- pyfda/plot_widgets/plot_tau_g.py
- pyfda/plot_widgets/plot_utils.py
Add icon and functionality for locking the displayed zoom.
> Plot lock zoom

- pyfda/compat.py
- pyfda/input_widgets/amplitude_specs.py
- pyfda/input_widgets/file_io.py
- pyfda/input_widgets/filter_coeffs.py
- pyfda/input_widgets/filter_info.py
- pyfda/input_widgets/filter_pz.py
- pyfda/input_widgets/filter_specs.py
- pyfda/input_widgets/freq_specs.py
- pyfda/input_widgets/freq_units.py
- pyfda/input_widgets/input_tab_widgets.py
- pyfda/input_widgets/input_tab_widgets_test.py
- pyfda/input_widgets/select_filter.py
- pyfda/input_widgets/target_specs.py
- pyfda/input_widgets/weight_specs.py
- pyfda/plot_widgets/plot_3d.py
- pyfda/plot_widgets/plot_hf.py
- pyfda/plot_widgets/plot_impz.py
- pyfda/plot_widgets/plot_phi.py
- pyfda/plot_widgets/plot_pz.py
- pyfda/plot_widgets/plot_tab_widgets.py
- pyfda/plot_widgets/plot_tab_widgets_empty.py
- pyfda/plot_widgets/plot_tau_g.py
- pyfda/plot_widgets/plot_utils.py
- pyfda/pyfdax.py
- pyfda/pyfdax_test.py
- pyfda/qrc_resources.py
This commit contains the start of PyQt5 compatibility, this allows
the pyfda pyqt application to work with PyQt4 or PyQt5.
This merge request is **NOT COMPLETE**.  Need to finish the pyqt5 compatibility integration.
> [WIP] start of pyqt5 compatibility.

- pyfda/input_widgets/filter_info.py
Filter info produced false pass / fail infos due to incorrect assignment of pass / stop bands.
> Fix filter info

- pyfda/input_widgets/freq_units.py
- pyfda/input_widgets/select_filter.py
- pyfda/pyfdax.py
Specify matplotlib backend for systems that have both PyQt4 and PyQt5 installed
> Specify matplotlib backend for systems that have both PyQt4 and PyQt5

- pyfda/filter_design/bessel.py
- pyfda/filter_design/butter.py
- pyfda/filter_design/cheby1.py
- pyfda/filter_design/cheby2.py
- pyfda/filter_design/common.py
- pyfda/filter_design/ellip.py
- pyfda/filter_design/equiripple.py
- pyfda/filter_design/firwin.py
- pyfda/filter_design/ma.py
- pyfda/filter_design/manual.py
- pyfda/filter_factory.py
- pyfda/filter_tree_builder.py
- pyfda/filterbroker.py
- pyfda/frozendict.py
- pyfda/input_widgets/filter_coeffs.py
- pyfda/input_widgets/filter_pz.py
- pyfda/input_widgets/filter_specs.py
- pyfda/input_widgets/freq_specs.py
- pyfda/input_widgets/input_tab_widgets.py
- pyfda/input_widgets/select_filter.py
- pyfda/input_widgets/target_specs.py
- pyfda/plot_widgets/plot_hf.py
- pyfda/pyfda_log.conf
- pyfda/pyfda_rc.py
- pyfda/pyfdax.py
This PR fixes #36 and #40 by completely redefining the structure of the dicts that specifiy the parameters for the filter design routines. 
It also fixes several small bugs with parameter handling.
The filter_tree dict now is a FrozenDict to avoid accidentally changing the dict after a shallow copy.
> Definition of target spec and other parameters for filter design routines

- pyfda/filter_design/ellip_zero.py
- pyfda/filter_design/filter_list.txt
- pyfda/filterbroker.py
- pyfda/input_widgets/file_io.py
- pyfda/input_widgets/filter_info.py
- pyfda/input_widgets/filter_pz.py
- pyfda/plot_widgets/plot_hf.py
- pyfda/plot_widgets/plot_impz.py
- pyfda/plot_widgets/plot_phi.py
- pyfda/plot_widgets/plot_pz.py
- pyfda/plot_widgets/plot_tau_g.py
- pyfda/pyfda_lib.py
- pyfda/pyfda_log.conf
This closes issue 77 (Shrink status window) and issue 75 (Enhance IIR elliptical filter) by creating a new elliptical filter that designs an IIR elliptical filter with zero phase.  It updates all of the filter response displays for the new filter.  It also can write out a custom text file that defines the filter design; this text file can be read by an outside filter application program to apply the filter to a saved signal data file.
> Add new zero phase elliptic filter

- pyfda/filterbroker.py
- pyfda/input_widgets/filter_coeffs.py
- pyfda/input_widgets/filter_pz.py
- pyfda/pyfda_lib.py
- pyfda/pyfda_qt_lib.py
This PR fixes several UI bugs (complex coefficients are converted to real when editing the table and some minor  flaws)
> Bugfixes in fiter_coefficient.py UI

- pyfda/filter_design/equiripple.py
- pyfda/filter_design/firwin.py
- pyfda/filter_design/ma.py
- pyfda/input_widgets/select_filter.py
- pyfda/plot_widgets/plot_3d.py
- pyfda/plot_widgets/plot_hf.py
- pyfda/plot_widgets/plot_impz.py
- pyfda/plot_widgets/plot_phi.py
- pyfda/plot_widgets/plot_pz.py
- pyfda/plot_widgets/plot_tau_g.py
- pyfda/plot_widgets/plot_utils.py
- pyfda/tests/widgets/tst_filter_coeffs.py
- pyfda/tests/widgets/tst_filter_coeffs_pytest.py
Make text entries more robust against wrong entries to prevent crashes.
> Ui robustness

- pyfda/filter_design/bessel.py
- pyfda/filter_design/ellip_zero.py
- pyfda/filter_factory.py
- pyfda/input_widgets/amplitude_specs.py
- pyfda/input_widgets/file_io.py
- pyfda/input_widgets/filter_coeffs.py
- pyfda/input_widgets/filter_info.py
- pyfda/input_widgets/filter_pz.py
- pyfda/input_widgets/filter_specs.py
- pyfda/input_widgets/select_filter.py
- pyfda/input_widgets/target_specs.py
- pyfda/plot_widgets/plot_pz.py
- pyfda/pyfda_lib.py
Add tooltips, fix order N problems (bessel order, FIR orders where coefficients are poorly defined, Elliptic filter with even order)
Add elliptic zero phase fixes, shrink name of filter, better name file output filename, remove zpk AntiCausal store and output
> Issues 81, 82, 83

- pyfda/plot_widgets/plot_3d.py
- pyfda/plot_widgets/plot_hf.py
- pyfda/plot_widgets/plot_impz.py
- pyfda/plot_widgets/plot_phi.py
- pyfda/plot_widgets/plot_pz.py
- pyfda/plot_widgets/plot_tau_g.py
- pyfda/plot_widgets/plot_utils.py
Disable plotting canvas too when widget is disabled (was confusing for the user before)
> Dont show disabled plt widgets

- pyfda/input_widgets/filter_coeffs.py
- pyfda/input_widgets/filter_pz.py
- pyfda/pyfda_io_lib.py
- pyfda/pyfda_log.conf
Coefficient and P/Z imports / exports in *.npy and *.npz format had several bugs.
Exporting to Microsemi FIR format has also been added.
> Fix npy and npz import / export bugs.

- AUTHORS.py
- pyfda/compat.py
- pyfda/filter_design/equiripple.py
- pyfda/filter_design/firwin.py
- pyfda/filter_factory.py
- pyfda/filter_tree_builder.py
- pyfda/filterbroker.py
- pyfda/frozendict.py
- pyfda/input_widgets/filter_coeffs.py
- pyfda/input_widgets/select_filter.py
- pyfda/mwe_splitter_tab_widgets.py
- pyfda/plot_widgets/plot_pz.py
- pyfda/plot_widgets/plot_tab_widgets.py
- pyfda/plot_widgets/plot_utils.py
- pyfda/pyfda_dirs.py
- pyfda/pyfda_fix_lib.py
- pyfda/pyfda_io_lib.py
- pyfda/pyfda_lib.py
- pyfda/pyfda_qt_lib.py
- pyfda/pyfda_rc.py
- pyfda/pyfdax.py
- pyfda/tests/test_pyfda_fix_lib.py
- pyfda/version.py
Make logger window resizable. This PR also fixes crashes that would occur sometimes while resizing the main window. Logger messages are also HTML formatted now.
> Resize logger window

- pyfda/plot_widgets/mpl_widget.py
- pyfda/plot_widgets/plot_impz.py
- pyfda/plot_widgets/plot_pz.py
- Fix several small bugs related to the navigation toolbar
- add feature: Plot |H(f)| around the unit circle in P/Z plot
> Plot overhaul

- pyfda/filter_design/firwin.py
- pyfda/input_widgets/amplitude_specs.py
- pyfda/input_widgets/filter_coeffs.py
- pyfda/input_widgets/filter_pz.py
- pyfda/input_widgets/freq_specs.py
- pyfda/input_widgets/input_tab_widgets.py
- pyfda/input_widgets/weight_specs.py
- pyfda/plot_widgets/plot_impz.py
- pyfda/plot_widgets/plot_impz_ui.py
- pyfda/plot_widgets/plot_tab_widgets.py
- pyfda/pyfda_lib.py
- pyfda/pyfdax.py
This PR adds the feature to analyse the filter response and stimulus in the frequency domain
It also fixes several bugs:
- complex values can now be entered into the coefficient widgets without crashing the app
- designing windowed filters with a kaiser window of minimum order works now in most of the cases
> Impz signals freq

- pyfda/filter_tree_builder.py
- pyfda/plot_widgets/mpl_widget.py
- pyfda/plot_widgets/plot_3d.py
- pyfda/plot_widgets/plot_hf.py
- pyfda/plot_widgets/plot_impz.py
- pyfda/plot_widgets/plot_phi.py
- pyfda/plot_widgets/plot_pz.py
- pyfda/plot_widgets/plot_tab_widgets.py
- pyfda/plot_widgets/plot_tau_g.py
Rewrite `plot_tab_widgets` so that plotting widgets can be defined and imported via a list of class names.
> Import plot widgets

- pyfda/input_widgets/filter_pz.py
- pyfda/plot_widgets/mwe_connect_signals.py
- pyfda/plot_widgets/plot_3d.py
- pyfda/plot_widgets/plot_hf.py
- pyfda/plot_widgets/plot_impz.py
- pyfda/plot_widgets/plot_phi.py
- pyfda/plot_widgets/plot_pz.py
- pyfda/plot_widgets/plot_tab_widgets.py
- pyfda/plot_widgets/plot_tau_g.py
Automatic rescaling of the plot after resizing the widget was broken after introducing new signal-slot system
> Fix automatic rescale

- pyfda/filterbroker.py
- pyfda/input_widgets/file_io.py
- pyfda/plot_widgets/plot_phi.py
This PR fixes #129 (various bugs in saving / loading filters)
> Fix file io

- pyfda/fixpoint_widgets/df1.py
- pyfda/input_widgets/input_fixpoint_specs.py
support for myHDL interface added in `setupHDL()`.  Floating point fixed point conversion not operational yet, I have commented out that part in `setupHDL()`.
> [WIP] added support for myHDL interface

- ressource/mime/applications/pyFDA.desktop
- ressource/pyFDA.appdata.xml
needed to create a flatpak package (pull request follows)
> add appdata and desktop file

- ressource/pyFDA.appdata.xml
I have to check if the format is correct (Don't know at the moment, so I have to check it out), just for preview at the moment.
> [WIP] add feature list to appdata.xml

- pyfda/plot_widgets/plot_impz_ui.py
- pyfda/pyfdax.py
Pass integers to Qt functions requiring integers.
> use integer sizes for qt

- ressource/linux/pyfda.appdata.xml
fix urls to the screenshots, it must point to the png it self not only to the github page
> fix urls to the screenshots

- ressource/linux/pyfda.appdata.xml
The previous urls worked, but for some reason the are not passing the test of the appdata checker
https://github.com/flathub/org.flatpak.Builder/issues/108
> Fix screenshot urls in appdata

- .github/workflows/build_flatpak.yml
I have to merge a few things first in the flathub repository
> use new approach to replace tag and url for testing

- MANIFEST.in
> Remove extra package directories from source distribution
